version: "3"
services:
  url-shortener:
    image: 'url-shortener:latest'
    container_name: url-shortener
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
networks:
  default:
    name: nginx-proxy-manager
    external: true
